#
- name: avahi - set host name
  hostname:
    name: "{{ project_name }}"

- name: avahi - install
  apt:
    name: "avahi-daemon"
    state: "present"

- name: avahi - fix "sudo, unable to resolve host"
  lineinfile:
    dest: "/etc/hosts"
    line: "127.0.0.1 {{ project_name }}"

- name: avahi - install avahi-aliases dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "syslog-ng"
    - "python-avahi"
    - "python-pip"

- name: avahi - install avahi-aliases
  shell: "pip install git+git://github.com/till/avahi-aliases.git@topics/make-it-run"
  args:
    creates: "/usr/local/bin/avahi-alias"

- name: avahi - ensure avahi-aliases directory exists
  file:
    path: "/etc/avahi/aliases.d"
    state: "directory"
    owner: "root"
    group: "root"
    mode: 0644
