#
- name: avahi - set host name
  hostname:
    name: "{{ project_name }}"

- name: avahi - install
  apt:
    name: "avahi-daemon"
    state: "present"

- name: avahi - install config
  template:
    src: "avahi-daemon.conf.j2"
    dest: "/etc/avahi/avahi-daemon.conf"
    owner: "root"
    group: "root"
    mode: 0644

- name: avahi - fix "sudo, unable to resolve host"
  lineinfile:
    dest: "/etc/hosts"
    line: "127.0.0.1 {{ project_name }}"

- name: avahi - restart daemon (forced)
  service:
    name: "avahi-daemon"
    state: "restarted"
