#
- name: bootstrap - install mandatory software
  apt:
    name: "{{ item }}"
    state: "latest"
  with_items:
    - mc
    - nano
    - htop
    - strace
    - vim
    - make
    - git
    - zip
    - unzip
    - supervisor

- name: bootstrap - install pavlik enable
  copy:
    src: "files/pavlik-enable"
    dest: "/usr/local/bin/pavlik-enable"
    owner: "root"
    group: "root"
    mode: 0755

- name: bootstrap - install docker cleanup script
  copy:
     src: "files/docker-cleanup"
     dest: "/usr/local/bin/docker-cleanup"
     owner: "root"
     group: "root"
     mode: 0755
