#
- name: bootstrap - install mandatory software
  apt:
    name: "{{ item }}"
    state: "latest"
  with_items:
    - mc
    - nano
    - htop
    - strace
    - vim
    - make
    - git
    - zip
    - unzip
    - python-pip
    - python-dev
    - libffi-dev
    - libssl-dev

# SNI (Subject Name Indication) extension to TLS
- name: bootstrap - install SNI SSL support for Python <= v2.6
  pip:
    name: "{{ item }}"
    state: "present"
  with_items:
    - pyopenssl
    - ndg-httpsclient
    - pyasn1
    - urllib3
