#
- name: bootstrap - install mandatory software
  apt:
    name: "{{ item }}"
    state: "latest"
  with_items:
    - mc
    - nano
    - htop
    - strace
    - vim
    - make
    - git
    - zip
    - unzip

- name: bootstap - install pavlik enable
  copy:
    src: "files/pavlik-enable"
    dest: "/usr/local/bin/pavlik-enable"
    owner: "root"
    group: "root"
    mode: 0755
