#
- name: bootstrap - install mandatory software
  apt:
    name: "{{ item }}"
    state: "latest"
  with_items:
    - mc
    - nano
    - htop
    - strace
    - vim
    - make
    - git
    - zip
    - unzip
